# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('rating', models.FloatField(default=0.0)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('flags', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Verified'), (1, 'Unverified'), (2, 'Deleted'), (3, 'Removed')], default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0.0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='item.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Reactable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('flags', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.IntegerField(choices=[(0, 'None'), (1, 'Like'), (2, 'Dislike'), (3, 'Flag')], default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('reactable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item.Reactable')),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='item.Item')),
            ],
            bases=('item.reactable',),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('reactable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item.Reactable')),
                ('picture', models.ImageField(upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='item.Item')),
            ],
            bases=('item.reactable',),
        ),
        migrations.AddField(
            model_name='reaction',
            name='reactable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Reactable'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('item', 'author')]),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('item', 'author')]),
        ),
    ]
